### ISSUE TITLE
Shared ruler & Y-Axis alignment

### ISSUE THREAD

**Issue by RisaI** [chartium/libchartium#3]
Share rulers across graphs. Perhaps make it configurable using string IDs (ruler groups).

![image](https://github.com/chartium/libchartium/assets/7413196/ad57f411-1b55-4388-b917-e1679a233471)

**Comment by m93a** [comment]
Pushnuto, ready na otestování na hlavní stránce EMC Dashboardu

**Comment by LafryCZ** [comment]
Více info na meetingu.

**Comment by LafryCZ** [comment]
pravitko zarovnano, jeste doresuju zarovnani zacatku grafu, dnes bude

**Comment by LafryCZ** [comment]
Michal zarovna. jeste to chce o 2mm dorovnat. jeste dnes udela

**Comment by LafryCZ** [comment]
stahnut update... blbe mi kresli data... zitra stahnu data od Alese a zkusim jeste pred meetingem

**Comment by LafryCZ** [comment]
Stazen novy update, vracim jelikoz se pravitko prestalo ukazovat.

**Comment by LafryCZ** [comment]
stále nezobrazuje.

**Comment by AlesSkypala** [comment]
Bude poreseno jamile bude novej release, behem dneska (18.04.2024) @m93a poresi a da vedet @LafryCZ

**Comment by LafryCZ** [comment]
stažen update, za me ok.
