### ISSUE TITLE
Add control buttons to graph (Full Screen, Download csv/png, show/hide legend)

### ISSUE THREAD

**Issue by AlesSkypala** [chartium/libchartium#41]
Same like insight controls in graph
![image](https://github.com/chartium/libchartium/assets/44568228/a37887b1-ac3f-489e-9e50-4987592f8bc3)

- Toggle Full screen
- Export to PNG
- Export to CSV
- Show/Hide Legend

**Comment by AlesSkypala** [comment]
Bude to tento tyden done, neco uz je (do 28.01.2024)

**Comment by Quacken8** [comment]
CSV není implemented, zbytek už je na libchartium main branch ✓

**Comment by AlesSkypala** [comment]
CSV budeme resit ted v tydnu. do dalsiho sprintu by melo byt hotovo

**Comment by Quacken8** [comment]
Ukazuje se, že export do CSV má mrtě edge cases a otrevných nuancí; vzhledem k prioritě issue tohle dávám na druhou kolej

**Comment by AlesSkypala** [comment]
Ja tam teda ty pozadovane tlacitka nevidim....(nepocitam csv...)? 


![Image](https://github.com/chartium/libchartium/assets/44568228/942fc209-dc4f-44ac-b87b-1b11228df536)

**Comment by AlesSkypala** [comment]
@Quacken8 : Dnes bude opraveno...

**Comment by LafryCZ** [comment]
Prosim o doplnění zrušení fullscreen tlačítkem ESC.

**Comment by AlesSkypala** [comment]
Znovu oteviram, nasel jsem nekolik veci:

- FullScreen tlacitko funguje 
- Proc tam jsou ty tlacitka Change Timezone/Autoscale Y axis, kdyz nic nedelaji? Nebo co maji delat? Vyhodit....
- Kdyz pouziju "FullScreen" na main dashboardu, tak se graf zobrazi, ale neni videt zadny tooltip pro konkretni krivky...?
  - Kdyz ve FullScreen z main dashboardu jedu k prave strane obrazovky/okna, zacne cely graf "odskakovat" od prave strany (zrejme proto, ze tam ma slider, ktery je ale z predchozi default stranky) - vypada to divne...:-/
- Kyz zkusim naopak fullscreen na grafu v Overview, otevre se nekde "na pozadi" - zkuste....
- Tooltip v detailu krivky ma porad oznaceni osy x: a y: )nikoliv date/value (stejne jako mame Insight)
- na overview grafech ted nevidim zadne krivky/traces, pouze prazdny graf
- legenda v grafu stale neni zarovnana do mrizky, ale rozhazena (kdyz nejsou nazvy stejne dlouhe)



![Image](https://github.com/chartium/libchartium/assets/44568228/400392aa-5936-4b32-9203-41199d4a42d2)

**Comment by AlesSkypala** [comment]
Ten prepinac Autoscale by byl dobrej tam mit - ale aby fungoval (ted nefunguje). Kazdopadne autoscale mit by default zapnuty....

**Comment by Quacken8** [comment]
related to #64, chartium/dashboard#86 #59

**Comment by LafryCZ** [comment]
Related to chartium/dashboard#36

**Comment by LafryCZ** [comment]
dnes Ondra odstraní tlačítka ChangeTimezone. Ostatní komenty jsou relevantní nebo jsou spojeny s jinou chybou.

**Comment by LafryCZ** [comment]
stazeno a proveden test... za me ok. muze se dat do release
