### ISSUE TITLE
Persistent treshold line(s) shown in graph

### ISSUE THREAD

**Issue by AlesSkypala** [chartium/libchartium#43]
Add possibility of show treshold persistent line in graph. 
Very usefull when needed to show some treshold (eg. 80% utilization). 
Treshold line should be maybe dot line with smaller intensity than standard trace line.
Please allow to have more than one trewshold line (sometimes there is required to have 2 or three treshlods)

**Comment by Quacken8** [comment]
Basic version implemented



![Image](https://github.com/chartium/libchartium/assets/78506690/2be5b317-7ce1-441a-8c7b-ecd9d40bc06b)
