### ISSUE TITLE
Treshold lines

### ISSUE THREAD

**Issue by AlesSkypala** [chartium/libchartium#58]
Add possibility to show treshold line(s) into line charts...
Now we have it like this:
![image](https://github.com/chartium/libchartium/assets/44568228/1a3a52d1-75de-48de-b3d3-f86aa032f2a6)

It's OK like t is now.
But if you think of some nicer ux, let's see what can we do with that.

Thanks

**Comment by AlesSkypala** [comment]
Zacal jsem delat, aktualne 70%, neni ready ale do 3 dnu bude hotovo.

**Comment by LafryCZ** [comment]
stale Ondra na tom pracuje.

**Comment by AlesSkypala** [comment]
Zatim v Dashboardu bug, jakmile #69  vyreseno, bude taky . 90% done

**Comment by AlesSkypala** [comment]
Tresholdy nejsou zatim carkovane (soucasne styly to neumoznuji.)
Bude resit @m93a  - dela predelani stylu, bude fungovat.
Funkcionalita je jiz hotova, ale styly to rozbiji.
Do pristiho tydne bude fixnuto (Michal)

**Comment by AlesSkypala** [comment]
Musel jsem predelat trace styles v libchartium. 
Zbyva udelat carkovane traces + palety barev + color spacing => tohle je cca 80% done, behem tohoto tydne bych mel dokoncit.

**Comment by AlesSkypala** [comment]
@m93a udelam behem dneska

**Comment by LafryCZ** [comment]
stazen update, za me ok, ready to release.

**Comment by AlesSkypala** [comment]
Jeste to otevriam - chtel bych to trosku jeste potunit => prosim tu linku udelat trosku tenci + v legende ta cara at se zobrazuje taky jako prerusovana, pujde to...? Ted se zobrazuje jako standardni trace.... 


![Image](https://github.com/chartium/libchartium/assets/44568228/4d60dd8e-eb44-4980-8760-04d27961133a)

**Comment by LafryCZ** [comment]
stažen update, za mě ok. ready to release
