### ISSUE TITLE
Visual enhancement of tooltip

### ISSUE THREAD

**Issue by AlesSkypala** [chartium/libchartium#59]
With 

- limit tooltip traces to max 3 => 
![image](https://github.com/chartium/libchartium/assets/44568228/d6bf4470-5792-4b80-b4d1-548018bf0627)
- on particualar trace tooltip, pls edit like it is in Insight
  - replace X + Y to "Time" + "Value"
  - add unit (IO/s)
  - format numbers (thousands)
  - avg value is not showed (NaN is dispayed)
- make tooltip and text smaller, inspiration => Insight
  - ![image](https://github.com/chartium/libchartium/assets/44568228/4755a34a-618c-42c1-88ce-383b0df5a230)

**Comment by AlesSkypala** [comment]
@Quacken8 Jedine co zbyva je udelat to hezke, pak zavreme.

**Comment by LafryCZ** [comment]
stazeno... prosim jeste upravit vzhled date: ...... prosim opravit text podle insight.  + nevim, proc mi zobrazuje avg:.

![Image](https://github.com/chartium/libchartium/assets/150274941/b8279f9f-1903-4782-861c-5651ad76358d)


![Image](https://github.com/chartium/libchartium/assets/150274941/75da51a4-de88-424c-8201-dc5d3e41f78d)

**Comment by AlesSkypala** [comment]
AVG hodnota - bude opravena v jinem issue => @m93a 
Co se tyce upravy vzhledu => 
- odskoceni date => ma byt pouze anglicky, nemusi byt sekunmdy, i casova zona (UTC)

@LafryCZ => udelat separe issue v insight na zarovnani textu

**Comment by LafryCZ** [comment]
neni mezera pod datem jako v dashboardu

![Image](https://github.com/chartium/libchartium/assets/150274941/f1c97039-40ce-436a-8bb2-54509f3f6333)

**Comment by AlesSkypala** [comment]
Melo by byt done, novy issue na Insight s odradkovanim datumu => @LafryCZ
