### ISSUE TITLE
Tooltips do not show enough decimal places

### ISSUE THREAD

**Issue by m93a** [chartium/libchartium#62]
![image](https://github.com/chartium/libchartium/assets/1671665/da1b8733-5be1-46d3-8488-ad804479e747)

We should adopt the same mechanism that axis ticks use to determine how many decimal places to display.

* [ ] Axis bubble fixed
* [x] Closest traces tooltip fixed
* [x] Trace stats tooltip fixed

**Comment by AlesSkypala** [comment]
zatim neni prio, kouknu na to tento sprint.

**Comment by LafryCZ** [comment]
stazen update, otestovano a pripraveno pro release.
