### ISSUE TITLE
If you hide all traces you get an error 

### ISSUE THREAD

**Issue by Quacken8** [chartium/libchartium#69]
smth to do with units of empty list being weird or idk

**Comment by m93a** [comment]
# I think this asks for a refactor
![image](https://github.com/chartium/libchartium/assets/1671665/7718368b-0137-4c2d-a4bd-a949f05c805f)

**Comment by AlesSkypala** [comment]
@m93a v tomto tydnu by melo byt hotovo, dnes/zitra idealne.

**Comment by LafryCZ** [comment]
dnes bude odesláno na testování

**Comment by LafryCZ** [comment]
stahnut update, testovano - ok - ready to release
