### ISSUE TITLE
Highlight points don't show correctly

### ISSUE THREAD

**Issue by Quacken8** [chartium/libchartium#74]
Wrong position on test page, totally missing in dashboard

perhaps something to do with relative positioning?

**Comment by Quacken8** [comment]
possibly connected to wrong axisValue?

![Image](https://github.com/chartium/libchartium/assets/78506690/137601fa-b3ab-4d66-afb1-05ee494218dc)

**Comment by AlesSkypala** [comment]
@LafryCZ pls zkus otestovat, pak zavrit

**Comment by LafryCZ** [comment]
stahnut update, stahl jsem i update Chartiumup - tečka není zobrazena v grafu

**Comment by AlesSkypala** [comment]
@Quacken8 Je to fixnuto, pouze neni verze v Dashboardu => Ondra to da behem dneska (18.4.,), pak da vedet @LafryCZ

**Comment by LafryCZ** [comment]
stazen update, tecka je zaseknuta na zacatku grafu. 

![Image](https://github.com/chartium/libchartium/assets/150274941/4d0ae20b-27f2-435d-a804-b5e8a930f16f)
![Image](https://github.com/chartium/libchartium/assets/150274941/8f1a1984-6f59-45a4-8087-11b7abf0ea04)

**Comment by AlesSkypala** [comment]
duplikat, resi se v ramci jineho issue
