### ISSUE TITLE
Date/time format incorrect in tooltip timestamp

### ISSUE THREAD

**Issue by AlesSkypala** [chartium/libchartium#79]
There is wrong timestamp shown in tooltip within libchartium graphs.
Only YEAR is shown, should be day/time

Pls fix

![Image](https://github.com/chartium/libchartium/assets/44568228/8f5fe00b-9120-46cc-a90d-d7be883ba452)

**Comment by AlesSkypala** [comment]
Tohle potrebuju fixnout asap, nejde v grafech urcit, ze na ktery den se divam...

**Comment by Quacken8** [comment]
Fixed in libchartium, soon™ to be in dashboard

**Comment by AlesSkypala** [comment]
Funkcionalita i vizual uz je ok, diky.
Jeste posledni vec => vytunit ten search/box - tak, aby byl dostatecne velkej, kdyz do neho uzivatel pise (aby videl celej string, ne jen cast - misto na te strance je). 
Idea je takova, ze kdyz do toho boxu zacnes psat, zobrazi se velkej radek (klidne do pulky obrazovky) a ty vidis kompletni cestu (ktera ma jak vidime treba 40/50 znaku).

Otazka je, jestli po kliku na enter/search to ma zmiznout a jen zustat v tom searchboxu zkracene, a nebo (coz mi prijde asi lepsi) at je to videt porad (aby uzivatel videl, co hleda/co zadal) a zmizne to az v okamziku, kdyz klikne na krizek
Zkus pls neco vymyslet jak by to slo udelat... :)

**Comment by AlesSkypala** [comment]
Ohh, sorry, koment k jinemu issue => prehodil jsem/smazal.
Kazdopadne tohle ted testuju a porad vidim to same, tzn. jen rok - je to opravdu v releasu, ktery si muzu stahnout (dev)?

**Comment by AlesSkypala** [comment]
jop. tohle uz vypada dobre, pls add to stable release...
