### ISSUE TITLE
Autoscale pro osu Y nefunguje korektne  na Main dashboard grafech

### ISSUE THREAD

**Issue by AlesSkypala** [chartium/libchartium#90]
Testovano na HP prostredi - po zoomu (vodorovne potazeni mysi) se nezmeni vubec skala na ose Y, zustava porad stejna. 
V overview to funguje dobre (tak, jak ma)

Default scale

![Image](https://github.com/chartium/libchartium/assets/44568228/a9411471-dbad-4c1f-9ac7-067d56a1c4b1)

vs potazeni vodorovne (zoom na ose X)

![Image](https://github.com/chartium/libchartium/assets/44568228/ff5e6b37-7d08-4a3c-b689-83ff51824a5f)

**Comment by LafryCZ** [comment]
za me ok, ready to release

**Comment by AlesSkypala** [comment]
Ahoj, za me to neni jeste ok.
@Quacken8 - jak poznam, ze je ten autoscale aktivni? 
Bavili jsme se o nejakem upozorneni (viz. koment vyse), ale nic to nedela....?

Ted kdyz to testuju, bylo by fajn tu ikonu nejak oznacit/zvyraznit - kdyz je to zaply. A kdyz nad to najedes, zobrazi se  "Autoscale Y axes ON" nebo neco podobneho.... Zkusis neco vymyslet...? 
Davam zpet do in-proigress

**Comment by AlesSkypala** [comment]
melo by byt ok, Ales otestuje

**Comment by AlesSkypala** [comment]
je to OK

**Comment by AlesSkypala** [comment]
Jeste jedna vec - muzes pls zmenit default autoscale v tech grafech aby byl ON? tzn. bude to autoscalovat - to bude default v grafu... Dik

**Comment by AlesSkypala** [comment]
tak jeste na zaklade meetingu - treshold linku obalit par px, aby byla videt vzdy (dnes jsou pripady, kdy se ztrati)
