### ISSUE TITLE
Area chart tooltips enhancements

### ISSUE THREAD

**Issue by AlesSkypala** [chartium/libchartium#91]
Pls add following features to libchartium area charts

- [x] persistent tooltip like in linecharts
- [x] indicator (point) on top of each area section (like in line chart)
- [ ] correct visibility of tooltip in some cases - like on printscreen - showing read+write tooltip but in the graph - there are different traces. This is probably becaues I used Fullscreen mode for this Area chart and on the background there is line-chart graph - and mouse is reacting to this non-visible graph... ;-)

Screen1 - tooltip

![Image](https://github.com/chartium/libchartium/assets/44568228/46f429cd-90cd-406f-b95c-d6ae762f1387)

Screen2  -bad Tooltip

![Image](https://github.com/chartium/libchartium/assets/44568228/5dea9b3b-d547-4355-8144-4d592ec33f27)

**Comment by RisaI** [comment]
Part 3 tracked as #92

**Comment by AlesSkypala** [comment]
Hele sorry ale ja to ani v posledni DEV verzi na tech area chartech ten tooltip nevidim (HP overview)...?

**Comment by RisaI** [comment]
Asi byl špatně zbuilděn npm release.

**Comment by AlesSkypala** [comment]
vypada uz ok, diky, pls to STABLE release
